-- ============================================================
-- SiteOps Database Schema
-- ============================================================

-- ------------------------------------------------------------
-- ENUM TYPES
-- ------------------------------------------------------------
CREATE TYPE user_role AS ENUM (
    'OPERATION_MANAGER',
    'PROJECT_MANAGER',
    'SITE_ENGINEER'
);

CREATE TYPE workflow_status AS ENUM (
    'PENDING',
    'IN_PROGRESS',
    'PAUSED',
    'COMPLETED',
    'CANCELLED'
);

-- ------------------------------------------------------------
-- TABLE: person
-- ------------------------------------------------------------
CREATE TABLE person (
    personID           INT             GENERATED BY DEFAULT AS IDENTITY,
    name               VARCHAR(100)    NOT NULL,
    position           VARCHAR(50)     NOT NULL,
    yearsOfExperience  INT             NULL,
    NIC                VARCHAR(30)     NOT NULL UNIQUE,

    CONSTRAINT pk_person PRIMARY KEY (personID)
);

-- ------------------------------------------------------------
-- TABLE: user
-- ------------------------------------------------------------
CREATE TABLE "user" (
    id           INT          GENERATED BY DEFAULT AS IDENTITY,
    personID     INT          NOT NULL,
    userName     VARCHAR(100) NOT NULL,
    email        VARCHAR(50)  NOT NULL UNIQUE,
    avatarImage  VARCHAR(255)     NULL,
    role         user_role    NOT NULL,

    CONSTRAINT pk_user          PRIMARY KEY (id),
    CONSTRAINT fk_user_person   FOREIGN KEY (personID)
        REFERENCES person (personID)
        ON UPDATE CASCADE ON DELETE RESTRICT
);

-- ------------------------------------------------------------
-- TABLE: project
-- ------------------------------------------------------------
CREATE TABLE project (
    projectID         INT             GENERATED BY DEFAULT AS IDENTITY,
    name              VARCHAR(100)    NOT NULL,
    locationLongitude DECIMAL(9, 6)       NULL,
    locationLatitude  DECIMAL(9, 6)       NULL,
    projectDiagram    VARCHAR(255)        NULL,
    projectManagerID  INT                 NULL,        -- FK, nullable
    status            workflow_status NOT NULL,

    CONSTRAINT pk_project              PRIMARY KEY (projectID),
    CONSTRAINT fk_project_manager      FOREIGN KEY (projectManagerID)
        REFERENCES "user" (id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

-- ------------------------------------------------------------
-- TABLE: activity
-- ------------------------------------------------------------
CREATE TABLE activity (
    activityID  INT          GENERATED BY DEFAULT AS IDENTITY,
    projectID   INT          NOT NULL,
    progress    INT          NOT NULL DEFAULT 0,
    description VARCHAR(255) NOT NULL,
    status      workflow_status NOT NULL,

    CONSTRAINT pk_activity         PRIMARY KEY (activityID),
    CONSTRAINT fk_activity_project FOREIGN KEY (projectID)
        REFERENCES project (projectID)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- TABLE: activity_assignment  (resolves person <-> activity M:N)
-- ------------------------------------------------------------
CREATE TABLE activity_assignment (
    assignmentID INT       GENERATED BY DEFAULT AS IDENTITY,
    activityID   INT       NOT NULL,
    personID     INT       NOT NULL,
    assignedAt   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_activity_assignment          PRIMARY KEY (assignmentID),
    CONSTRAINT uq_activity_assignment          UNIQUE (activityID, personID),
    CONSTRAINT fk_assignment_activity          FOREIGN KEY (activityID)
        REFERENCES activity (activityID)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_assignment_person            FOREIGN KEY (personID)
        REFERENCES person (personID)
        ON UPDATE CASCADE ON DELETE CASCADE
);

-- ------------------------------------------------------------
-- TABLE: activity_log_entry
-- ------------------------------------------------------------
CREATE TABLE activity_log_entry (
    logEntryID       INT          GENERATED BY DEFAULT AS IDENTITY,
    activityID       INT          NOT NULL,
    timestamp        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    description      VARCHAR(255) NOT NULL,
    siteEngineerID   INT          NOT NULL,
    updatedProgress  INT              NULL,
    evidencePhoto    VARCHAR(255)     NULL,

    CONSTRAINT pk_activity_log_entry          PRIMARY KEY (logEntryID),
    CONSTRAINT fk_log_entry_activity          FOREIGN KEY (activityID)
        REFERENCES activity (activityID)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_log_entry_site_engineer     FOREIGN KEY (siteEngineerID)
        REFERENCES "user" (id)
        ON UPDATE CASCADE ON DELETE RESTRICT
);