-- ============================================================
-- SiteOps Database Schema Update 002
-- Adds Zones to Activities and establishes Material Tracking
-- ============================================================

-- 1. Add Zone/Sub-Area data directly to the Activity table
ALTER TABLE activity
ADD COLUMN zoneName VARCHAR(100) NULL,
ADD COLUMN zoneLatitude DECIMAL(9, 6) NULL,
ADD COLUMN zoneLongitude DECIMAL(9, 6) NULL;


-- 2. ENUM for Material Measurement Units
CREATE TYPE material_unit AS ENUM (
    'MT',         -- Metric Tonnes (Steel, Base Course)
    'CUBES',      -- Cubes (Sand, Aggregate)
    'BAGS',       -- Bags (Cement)
    'UNITS',      -- Units/Pieces (Bricks, Piles)
    'SQ_METERS'   -- Square Meters (Tiles)
);


-- 3. TABLE: material_catalog (Master list of enterprise materials)
CREATE TABLE material_catalog (
    materialID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL,
    unit material_unit NOT NULL,
    companyTotalStock DECIMAL(12, 2) NOT NULL DEFAULT 0.00
);


-- 4. TABLE: project_material_inventory (Stock allocated to specific projects)
CREATE TABLE project_material_inventory (
    inventoryID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projectID INT NOT NULL REFERENCES project(projectID) ON DELETE CASCADE,
    materialID INT NOT NULL REFERENCES material_catalog(materialID) ON DELETE CASCADE,
    allocatedStock DECIMAL(12, 2) NOT NULL DEFAULT 0.00,
    
    -- Ensure a project only has one inventory record per material type
    CONSTRAINT uq_project_material UNIQUE (projectID, materialID)
);


-- 5. TABLE: material_consumption_log (Daily burn rate logged by engineers)
CREATE TABLE material_consumption_log (
    logID INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activityID INT NOT NULL REFERENCES activity(activityID) ON DELETE CASCADE,
    materialID INT NOT NULL REFERENCES material_catalog(materialID) ON DELETE CASCADE,
    quantityUsed DECIMAL(10, 2) NOT NULL,
    dateRecorded DATE NOT NULL DEFAULT CURRENT_DATE,
    loggedBy INT NOT NULL REFERENCES "user"(id) ON DELETE RESTRICT
);
