-- Let's remove the column projectManagerID from project table
ALTER TABLE project DROP COLUMN projectManagerID;
-- Now we need to create a new table to represent the M:N relationship between projects and people (project assignments)
CREATE TABLE project_assignment (
    assignmentID INT       GENERATED BY DEFAULT AS IDENTITY,
    projectID    INT       NOT NULL,
    personID     INT       NOT NULL,
    assignedAt   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_project_assignment          PRIMARY KEY (assignmentID),
    CONSTRAINT uq_project_assignment          UNIQUE (projectID, personID),
    CONSTRAINT fk_project_assignment_project  FOREIGN KEY (projectID)
        REFERENCES project (projectID)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_project_assignment_person   FOREIGN KEY (personID)
        REFERENCES person (personID)
        ON UPDATE CASCADE ON DELETE CASCADE
);