-- ============================================================
-- SiteOps Database Schema Update 005
-- Adds geographic coordinates to project zones
-- ============================================================

-- Add latitude, longitude, and markerLabel columns to project_zone table
-- If the table doesn't exist, this creates it
-- If columns already exist, they will be ignored (with IF NOT EXISTS)

CREATE TABLE IF NOT EXISTS project_zone (
    zoneid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projectid INT NOT NULL REFERENCES project(projectid) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(255) NULL,
    activity VARCHAR(255) NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'pending',
    progress INT NOT NULL DEFAULT 0,
    latitude DECIMAL(9, 6) NULL,
    longitude DECIMAL(9, 6) NULL,
    markerlabel VARCHAR(100) NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Add columns if they don't already exist (for existing project_zone tables)
-- PostgreSQL doesn't have IF NOT EXISTS for columns, so we use a custom approach
-- Or simply comment these out if the columns already exist:

-- ALTER TABLE project_zone
-- ADD COLUMN IF NOT EXISTS latitude DECIMAL(9, 6) NULL;

-- ALTER TABLE project_zone
-- ADD COLUMN IF NOT EXISTS longitude DECIMAL(9, 6) NULL;

-- ALTER TABLE project_zone
-- ADD COLUMN IF NOT EXISTS markerlabel VARCHAR(100) NULL;

-- Sample data for testing:
-- INSERT INTO project_zone (projectid, name, description, activity, status, progress, latitude, longitude, markerlabel)
-- VALUES 
--   (1, 'Foundation Pit', 'Excavation and foundation work', 'Excavation', 'in_progress', 45, 6.9271, 80.7789, 'Zone A'),
--   (1, 'Structural Frame', 'Steel frame installation', 'Framing', 'pending', 10, 6.9275, 80.7795, 'Zone B'),
--   (1, 'Finishing', 'Interior finishing work', 'Finishing', 'pending', 0, 6.9265, 80.7785, 'Zone C');
