-- ============================================================
-- SiteOps Database Schema Update 006
-- Equipment Registry & Asset Management
-- ============================================================

-- 1. TABLE: equipment_class (Categorization of heavy machinery)
CREATE TABLE equipment_class (
    classid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT NULL
);

-- 2. TABLE: equipment_item (Individual machinery units)
CREATE TABLE equipment_item (
    itemid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    classid INT NOT NULL REFERENCES equipment_class(classid) ON DELETE CASCADE,
    projectid INT REFERENCES project(projectid) ON DELETE SET NULL,
    serial_number VARCHAR(50) UNIQUE NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'operational', -- 'operational', 'under_repair', 'retired'
    daily_rate DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
    next_service_date DATE NULL,
    last_service_date DATE NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. TABLE: equipment_assignment (Historical & Current Assignments)
CREATE TABLE equipment_assignment (
    assignmentid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    itemid INT NOT NULL REFERENCES equipment_item(itemid) ON DELETE CASCADE,
    activityid INT REFERENCES activity(activityid) ON DELETE SET NULL,
    zoneid INT REFERENCES project_zone(zoneid) ON DELETE SET NULL,
    start_date DATE NOT NULL,
    end_date DATE NULL,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ------------------------------------------------------------
-- SEED DATA: Equipment Classes
-- ------------------------------------------------------------
INSERT INTO equipment_class (name, description) VALUES
('Lifting & Cranes', 'Tower cranes, mobile cranes, and crawler cranes for vertical transport'),
('Earthmoving', 'Excavators, bulldozers, and graders for site preparation'),
('Concreting', 'Mixer trucks and pump systems for heavy concrete work'),
('Foundation & Piling', 'Rigs and hammers for deep foundation work'),
('Logistics & Transport', 'Dump trucks and flatbeds for material movement'),
('Compaction', 'Rollers and compactors for soil stability');

-- ------------------------------------------------------------
-- SEED DATA: Equipment Items (Access Engineering Scale)
-- ------------------------------------------------------------

-- Project ID 1 is assumed to be the active project
DO $$
DECLARE
    lifting_cid INT;
    earth_cid INT;
    concrete_cid INT;
    found_cid INT;
    logistics_cid INT;
    compaction_cid INT;
    pid INT := 1; -- Assuming project ID 1 exists
BEGIN
    SELECT classid INTO lifting_cid FROM equipment_class WHERE name = 'Lifting & Cranes';
    SELECT classid INTO earth_cid FROM equipment_class WHERE name = 'Earthmoving';
    SELECT classid INTO concrete_cid FROM equipment_class WHERE name = 'Concreting';
    SELECT classid INTO found_cid FROM equipment_class WHERE name = 'Foundation & Piling';
    SELECT classid INTO logistics_cid FROM equipment_class WHERE name = 'Logistics & Transport';
    SELECT classid INTO compaction_cid FROM equipment_class WHERE name = 'Compaction';

    -- Lifting
    INSERT INTO equipment_item (name, classid, projectid, serial_number, daily_rate, next_service_date, status) VALUES
    ('Potain MDT 319 Tower Crane', lifting_cid, pid, 'TC-P-319-01', 1500.00, '2026-06-15', 'operational'),
    ('Potain MDT 219 Tower Crane', lifting_cid, pid, 'TC-P-219-02', 1200.00, '2026-05-20', 'operational'),
    ('Liebherr LTM 1100 Mobile Crane', lifting_cid, pid, 'MC-L-1100-01', 950.00, '2026-05-10', 'operational'),
    ('Liebherr LTM 1050 Mobile Crane', lifting_cid, pid, 'MC-L-1050-02', 750.00, '2026-04-30', 'operational');

    -- Earthmoving
    INSERT INTO equipment_item (name, classid, projectid, serial_number, daily_rate, next_service_date, status) VALUES
    ('Volvo EC480 Hard-Rock Excavator', earth_cid, pid, 'EX-V-480-01', 850.00, '2026-05-12', 'operational'),
    ('Volvo EC480 Hard-Rock Excavator', earth_cid, pid, 'EX-V-480-02', 850.00, '2026-06-05', 'operational'),
    ('Caterpillar 320 Next Gen', earth_cid, pid, 'EX-C-320-03', 550.00, '2026-05-01', 'operational'),
    ('Caterpillar 320 Next Gen', earth_cid, pid, 'EX-C-320-04', 550.00, '2026-04-20', 'under_repair'),
    ('Kubota KX080-4 Mini Excavator', earth_cid, pid, 'EX-K-080-05', 300.00, '2026-06-10', 'operational'),
    ('Caterpillar D6 Dozer', earth_cid, pid, 'DZ-C-D6-01', 900.00, '2026-05-25', 'operational'),
    ('Komatsu GD655 Motor Grader', earth_cid, pid, 'GR-K-655-01', 1100.00, '2026-07-01', 'operational');

    -- Concreting
    INSERT INTO equipment_item (name, classid, projectid, serial_number, daily_rate, next_service_date, status) VALUES
    ('Putzmeister 36m Boom Pump', concrete_cid, pid, 'CP-P-36-01', 1800.00, '2026-05-05', 'operational'),
    ('Mack Granite Mixer Truck X1', concrete_cid, pid, 'MX-M-G1-01', 450.00, '2026-05-15', 'operational'),
    ('Mack Granite Mixer Truck X2', concrete_cid, pid, 'MX-M-G1-02', 450.00, '2026-05-15', 'operational'),
    ('Mack Granite Mixer Truck X3', concrete_cid, pid, 'MX-M-G1-03', 450.00, '2026-04-24', 'under_repair'),
    ('Mack Granite Mixer Truck X4', concrete_cid, pid, 'MX-M-G1-04', 450.00, '2026-05-22', 'operational');

    -- Foundation
    INSERT INTO equipment_item (name, classid, projectid, serial_number, daily_rate, next_service_date, status) VALUES
    ('Casagrande B175 Piling Rig', found_cid, pid, 'PR-C-175-01', 2500.00, '2026-06-01', 'operational'),
    ('Mait HR130 Rotatory Rig', found_cid, pid, 'PR-M-130-02', 2100.00, '2026-05-28', 'operational');

    -- Logistics
    INSERT INTO equipment_item (name, classid, projectid, serial_number, daily_rate, next_service_date, status) VALUES
    ('Scania G440 Tipper Truck', logistics_cid, pid, 'DT-S-440-01', 400.00, '2026-06-10', 'operational'),
    ('Scania G440 Tipper Truck', logistics_cid, pid, 'DT-S-440-02', 400.00, '2026-06-10', 'operational'),
    ('Isuzu FTR Flatbed', logistics_cid, pid, 'FT-I-FTR-01', 350.00, '2026-08-15', 'operational');

END $$;
