-- ============================================================
-- SiteOps Database Schema Update 007
-- Equipment Observability & Reliability Tracking
-- ============================================================

-- 1. Remove financial accounting focus (Daily Rates)
ALTER TABLE equipment_item DROP COLUMN IF EXISTS daily_rate;

-- 2. Add Technical Specifications
-- Uses JSONB to allow flexible attributes (e.g., lift capacity for cranes vs. bucket size for excavators)
ALTER TABLE equipment_item ADD COLUMN IF NOT EXISTS technical_specs JSONB DEFAULT '{}'::jsonb;

-- 3. Create Maintenance & Reliability Log
-- This tracks the history of an asset's breakdowns and services to determine its reliability
CREATE TABLE IF NOT EXISTS equipment_maintenance_log (
    logid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    itemid INT NOT NULL REFERENCES equipment_item(itemid) ON DELETE CASCADE,
    issue_type VARCHAR(50) NOT NULL, -- 'preventive_service', 'breakdown', 'inspection'
    description TEXT NOT NULL,
    reported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP NULL,
    downtime_hours INT NULL,
    resolution_notes TEXT NULL
);

-- ============================================================
-- SEED DATA: Update existing assets to support the new features
-- ============================================================

DO $$
BEGIN
    -- Seed Technical Specs for Cranes
    UPDATE equipment_item SET technical_specs = '{"max_lift_capacity": "16 Tons", "max_reach": "70m", "power_type": "Electric"}'::jsonb WHERE name LIKE '%Tower Crane%';
    UPDATE equipment_item SET technical_specs = '{"max_lift_capacity": "100 Tons", "max_reach": "52m", "power_type": "Diesel"}'::jsonb WHERE name LIKE '%Mobile Crane%';

    -- Seed Technical Specs for Earthmoving
    UPDATE equipment_item SET technical_specs = '{"bucket_capacity": "2.5 m3", "operating_weight": "48 Tons"}'::jsonb WHERE name LIKE '%Excavator%';

    -- Seed Technical Specs for Concreting
    UPDATE equipment_item SET technical_specs = '{"drum_capacity": "8 m3", "chute_length": "3.5m"}'::jsonb WHERE name LIKE '%Mixer%';
    
    -- Seed Technical Specs for Foundation
    UPDATE equipment_item SET technical_specs = '{"max_drilling_depth": "60m", "max_torque": "175 kNm"}'::jsonb WHERE name LIKE '%Rig%';
END $$;

-- Seed some historical maintenance logs to demonstrate "Asset Reliability History"
DO $$
DECLARE
    mixer_id INT;
    excavator_id INT;
BEGIN
    -- Get specific items based on the seed data from migration 006
    SELECT itemid INTO mixer_id FROM equipment_item WHERE name = 'Mack Granite Mixer Truck X3' LIMIT 1;
    SELECT itemid INTO excavator_id FROM equipment_item WHERE name = 'Caterpillar 320 Next Gen' LIMIT 1;

    IF mixer_id IS NOT NULL THEN
        -- Add past resolved breakdown
        INSERT INTO equipment_maintenance_log (itemid, issue_type, description, reported_at, resolved_at, downtime_hours, resolution_notes)
        VALUES (mixer_id, 'breakdown', 'Hydraulic pump failure during pour', CURRENT_TIMESTAMP - INTERVAL '30 days', CURRENT_TIMESTAMP - INTERVAL '28 days', 48, 'Replaced main hydraulic pump assembly');
        
        -- Add current unresolved breakdown
        INSERT INTO equipment_maintenance_log (itemid, issue_type, description, reported_at, resolved_at, downtime_hours, resolution_notes)
        VALUES (mixer_id, 'breakdown', 'Engine stalling under load', CURRENT_TIMESTAMP - INTERVAL '2 days', NULL, NULL, NULL);
    END IF;

    IF excavator_id IS NOT NULL THEN
         -- Add routine service history
         INSERT INTO equipment_maintenance_log (itemid, issue_type, description, reported_at, resolved_at, downtime_hours, resolution_notes)
        VALUES (excavator_id, 'preventive_service', 'Scheduled 500-hour engine service', CURRENT_TIMESTAMP - INTERVAL '60 days', CURRENT_TIMESTAMP - INTERVAL '59 days', 8, 'Routine oil, filter, and track tensioning completed');
    END IF;
END $$;
