-- ============================================================
-- SiteOps Database Schema Update 008
-- Subtasks, subtask progress logs, activity progress sync
-- ============================================================

-- Deadline on activity (skip if your Supabase project already has this column)
ALTER TABLE activity
ADD COLUMN IF NOT EXISTS deadline DATE NULL;

-- ------------------------------------------------------------
-- TABLE: subtask
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS subtask (
    subtaskid     INT GENERATED BY DEFAULT AS IDENTITY,
    activityid    INT          NOT NULL,
    title         VARCHAR(255) NOT NULL,
    duedate       DATE             NULL,
    completed     BOOLEAN      NOT NULL DEFAULT FALSE,
    displayorder  INT          NOT NULL DEFAULT 0,
    completedat   TIMESTAMP        NULL,
    createdat     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updatedat     TIMESTAMP        NULL,

    CONSTRAINT pk_subtask PRIMARY KEY (subtaskid),
    CONSTRAINT fk_subtask_activity FOREIGN KEY (activityid)
        REFERENCES activity (activityid)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_subtask_activity ON subtask (activityid);

-- ------------------------------------------------------------
-- TABLE: subtask_log_entry
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS subtask_log_entry (
    logentryid    INT GENERATED BY DEFAULT AS IDENTITY,
    subtaskid     INT          NOT NULL,
    description   VARCHAR(255) NOT NULL,
    createdby     INT              NULL,
    evidencephoto VARCHAR(255)     NULL,
    createdat     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_subtask_log_entry PRIMARY KEY (logentryid),
    CONSTRAINT fk_subtask_log_subtask FOREIGN KEY (subtaskid)
        REFERENCES subtask (subtaskid)
        ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_subtask_log_user FOREIGN KEY (createdby)
        REFERENCES "user" (id)
        ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_subtask_log_subtask ON subtask_log_entry (subtaskid);

-- ------------------------------------------------------------
-- Sync activity.progress from completed subtasks
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION sync_activity_progress_from_subtasks()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_activity_id INT;
    v_progress INT;
BEGIN
    v_activity_id := COALESCE(NEW.activityid, OLD.activityid);

    SELECT COALESCE(
        ROUND(
            100.0 * COUNT(*) FILTER (WHERE s.completed = TRUE)
            / NULLIF(COUNT(*), 0)
        )::INT,
        0
    )
    INTO v_progress
    FROM subtask s
    WHERE s.activityid = v_activity_id;

    UPDATE activity a
    SET progress = v_progress,
        updatedat = CURRENT_TIMESTAMP
    WHERE a.activityid = v_activity_id;

    RETURN COALESCE(NEW, OLD);
END;
$$;

DROP TRIGGER IF EXISTS trg_subtask_sync_activity_progress ON subtask;

CREATE TRIGGER trg_subtask_sync_activity_progress
AFTER INSERT OR UPDATE OF completed OR DELETE ON subtask
FOR EACH ROW
EXECUTE PROCEDURE sync_activity_progress_from_subtasks();

-- Example seed (replace activityid values with yours):
-- INSERT INTO subtask (activityid, title, duedate, completed, displayorder) VALUES
--   (1, 'Site Preparation', CURRENT_DATE, TRUE, 1),
--   (1, 'Excavation', CURRENT_DATE + 4, TRUE, 2),
--   (1, 'Foundation Concrete', CURRENT_DATE + 11, FALSE, 3),
--   (1, 'Curing & Testing', CURRENT_DATE + 14, FALSE, 4);
